name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['1.19', '1.19.1', '1.19.2', '1.19.3', '1.19.4', '1.20', '1.20.1', '1.20.2', '1.20.3', '1.20.4', '1.20.5', '1.20.6', '1.21', '1.21.1', '1.21.2', '1.21.3', '1.21.4']
      fail-fast: true
    steps:
      - name: Check out project
        if: success()
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        if: success()
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'

      - name: Setup Gradle
        if: success()
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.12

      - name: Execute tests
        if: success()
        run: gradle test -Pv=${{ matrix.version }}

      - name: Build
        if: success()
        run: gradle remapJar -Pv=${{ matrix.version }}

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.version }}
          path: |
            **/libs/allay-follow-always-*.jar

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out metadata
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            README.md
            CHANGELOG.md
            LICENSE

      - name: Download artifacts
        if: success()
        uses: actions/download-artifact@v4

      - name: Release on github
        if: success() # No git tag check, since action-gh-release fails if not valid
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/libs/allay-follow-always-*.jar
            README.md
            CHANGELOG.md
            LICENSE
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
          fail_on_unmatched_files: true

  publish:
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        version: ['1.19', '1.19.1', '1.19.2', '1.19.3', '1.19.4', '1.20', '1.20.1', '1.20.2', '1.20.3', '1.20.4', '1.20.5', '1.20.6', '1.21', '1.21.1', '1.21.2', '1.21.3', '1.21.4']
      fail-fast: true
    steps:
      - name: Check out metadata
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            CHANGELOG.md

      - name: Download artifact
        if: success()
        uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.version }}

      - name: Publish on modrinth
        if: success() && startsWith(github.ref, 'refs/tags/') # Failsafe check
        # See https://github.com/Kir-Antipov/mc-publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: allay-follow-always
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: false
          files: |
            **/libs/allay-follow-always-*.jar
          name: Allay Follow Always ${{ github.ref_name }}
          version: ${{ github.ref_name }}+${{ matrix.version }}
          version-type: "${{ contains(github.ref_name, 'SNAPSHOT') && 'alpha' || 'release' }}"
          changelog-file: CHANGELOG.md
          #loaders: fabric
          game-versions: "=${{ matrix.version }}"
          #dependencies:

  publish_readme:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Check out metadata
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            README.md

      - name: Update readme
        if: success()
        run: |
          readme="$(sed 's/\\/\\\\/g; s/"/\\"/g; s/$/\\n/' README.md)"
          json="{ \"body\": \"$readme\" }"
          echo "$json" | curl -XPATCH -H "Authorization: ${{ secrets.MODRINTH_TOKEN }}" -H "Content-type: application/json" -d @- 'https://api.modrinth.com/v2/project/allay-follow-always'
